apiVersion: apps/v1
kind: Deployment
metadata:
  name: engineering-teams-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: engineering-teams
  template:
    metadata:
      labels:
        app: engineering-teams
    spec:
      containers:
      - name: engineering-teams
        image: engineering_teams:latest
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
