apiVersion: v1
kind: Service
metadata:
  name: engineering-teams-service
spec:
  selector:
    app: engineering-teams
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
